### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JCqiu** [NastyZ98/angular6-dynamic-dashboard#1]
The clone project was reported wrong after operation.

![qq 20181105160406](https://user-images.githubusercontent.com/16211027/47985418-7bf43e80-e114-11e8-9861-884e60b1bcea.png)

**Comment by NastyZ98** [comment]
Hi,
These problems doesn't affect the functionalities of the project. I know they are here but I don't have time to change the CSS framework, these errors are created by third parties frameworks (ChartJS and the CSS framework).

Next time try to say hello and put a detailled title.

Regards, Nathan.

**Comment by JCqiu** [comment]
@NastyZ98 thanks Nathan

**Comment by NastyZ98** [comment]
I will update the actual projet to Angular 7 and remove the CSS framework and CharJS lib.
